/*
	Milyn - Copyright (C) 2006

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License (version 2.1) as published by the Free Software
	Foundation.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

	See the GNU Lesser General Public License for more details:
	http://www.gnu.org/licenses/lgpl.txt
*/
package org.milyn.ejc.classes;

import java.util.Map;
import java.util.HashMap;

/**
 * JJavaClass inherits JClass but is used for separating classes found in
 * java library that should not be generated by {@link org.milyn.ejc.BeanWriter}.
 * 
 * @author bardl 
 */
public class JJavaClass extends JClass {

    private static Map<String,String> classes;

    public static final JJavaClass STRING = new JJavaClass(JPackage.JAVA_LANG, "String");
    public static final JJavaClass LIST = new JJavaClass(JPackage.JAVA_UTIL, "List");
    public static final JJavaClass ARRAY_LIST = new JJavaClass(JPackage.JAVA_UTIL, "ArrayList", null, LIST);    

    static {
        classes = new HashMap<String,String>();
        classes.put("Date", "java.util");        
    }

    public JJavaClass(JPackage classPackage, String name, JType genericType, JType interfaceOf) {
        super(classPackage, name, genericType, interfaceOf);
    }

    public JJavaClass(JPackage classPackage, String name) {        
        super(classPackage, name);
    }

    public static JPackage getPackageForClass(Class javaClass) {
        if (javaClass == null) {
            return null;
        }
        return new JPackage(javaClass.getPackage().getName());
    }
}
