<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cuscar"
    nsURI="http://smooks.org/UNEDI/D99AUN/CUSCAR" nsPrefix="cuscar">
  <eAnnotations source="smooks-mapping-data">
    <details key="description.name" value="CUSCAR"/>
    <details key="description.version" value="D:99A:UN"/>
    <details key="delimeters.segment" value="&amp;#39;!$"/>
    <details key="delimeters.component" value=":"/>
    <details key="delimeters.field" value="+"/>
    <details key="delimeters.fieldRepeat"/>
    <details key="delimeters.escape" value="?"/>
    <details key="delimeters.ignoreCLRF" value="true"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup17">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 17: AUT-DTM-RFF&#xA;       A group of segments to specify the authentication of the&#xA;       message."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup17"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AUT" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//AuthenticationResult"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Authentication_result"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="AUT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DTM"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="RFF"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup11">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 11: NAD-DTM-RFF-SG12&#xA;             A group of segments to identify the parties, contacts and&#xA;             related references and dates."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup11"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NAD" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//NameAndAddress"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Name_and_address"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="NAD"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DTM"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="RFF"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup12" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup12" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_12"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
        <details key="segcode" value="CTA"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup9">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 9:  TDT-LOC-DTM-MEA-SG10&#xA;             A group of segments to identify details of onward&#xA;             carriage for each consignment."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup9"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TDT" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//DetailsOfTransport"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Details_of_transport"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="TDT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="LOC"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DTM"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MEA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Measurements"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Measurements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="MEA"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup10" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup10" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_10"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
        <details key="segcode" value="RFF"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CUSCAR">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CUSCAR"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BGM" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//BeginningOfMessage"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Beginning_of_message"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="BGM"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DTM"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="LOC"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="QTY" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Quantity"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Quantity"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="QTY"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup1" upperBound="99"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup1" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_1"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="group"/>
        <details key="segcode" value="RFF"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup2" upperBound="99"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup2" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_2"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="group"/>
        <details key="segcode" value="NAD"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FTX" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//FreeText"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Free_text"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="FTX"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup4" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup4" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_4"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
        <details key="segcode" value="TDT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GIS" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//GeneralIndicator"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="General_indicator"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="GIS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup5" upperBound="9999"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup5" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_5"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="group"/>
        <details key="segcode" value="EQD"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CNT" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//ControlTotal"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Control_total"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="CNT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup7" upperBound="9999"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup7" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_7"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="group"/>
        <details key="segcode" value="CNI"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup17" eType="ecore:EClass cuscar.ecore#//SegmentGroup17"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_17"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="group"/>
        <details key="segcode" value="AUT"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup4">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 4:  TDT-LOC-DTM&#xA;       A group of segments to identify details of transport, locations&#xA;       and associated dates/times."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup4"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TDT" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//DetailsOfTransport"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Details_of_transport"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="TDT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="LOC"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DTM"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup2">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 2:  NAD-SG3&#xA;       A group of segments to identify contact and communication&#xA;       contact information related to the person responsible for the&#xA;       cargo reporting."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup2"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NAD" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//NameAndAddress"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Name_and_address"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="NAD"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup3" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup3" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_3"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
        <details key="segcode" value="CTA"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup14">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 14: GID-PAC-HAN-FTX-MEA-MOA-SGP-DGS-PCI-&#xA;                               CST-LOC-TMD-SG15-SG16&#xA;             A group of segments specifying goods item details&#xA;             including number and type of packages, handling&#xA;             instructions, quantity variances, package identification,&#xA;             goods description, monetary amounts, measurements,&#xA;             indicators for split goods placement, indicator for&#xA;             dangerous goods, status of the goods, documents."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup14"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GID" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//GoodsItemDetails"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Goods_item_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="GID"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PAC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Package"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Package"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="PAC"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="HAN" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//HandlingInstructions"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Handling_instructions"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="HAN"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FTX" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//FreeText"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Free_text"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="FTX"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MEA" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//Measurements"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Measurements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="MEA"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MOA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//MonetaryAmount"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Monetary_amount"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="MOA"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SGP" upperBound="9999"
        eType="ecore:EClass commonDefinitions.ecore#//SplitGoodsPlacement" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Split_goods_placement"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="SGP"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DGS" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DangerousGoods"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Dangerous_goods"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DGS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PCI" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//PackageIdentification"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Package_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="PCI"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CST" eType="ecore:EClass commonDefinitions.ecore#//CustomsStatusOfGoods"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Customs_status_of_goods"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="CST"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="LOC"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TMD" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//TransportMovementDetails"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Transport_movement_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="TMD"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup15" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup15" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_15"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
        <details key="segcode" value="GIS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup16" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup16" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_16"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
        <details key="segcode" value="QTY"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup12">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 12: CTA-COM&#xA;                A group of segments identifying a contact and its&#xA;                communication related to the party."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup12"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CTA" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//ContactInformation"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Contact_information"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="CTA"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="COM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//CommunicationContact"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Communication_contact"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="COM"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup6">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 6:  TMP-RNG&#xA;          A group of segments to indicate temperature information."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup6"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TMP" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Temperature"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Temperature"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="TMP"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RNG" eType="ecore:EClass commonDefinitions.ecore#//RangeDetails"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Range_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="RNG"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup16">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 16: QTY-FTX&#xA;                A group of segments to specify, at goods item level,&#xA;                the quantity manifested, quantity landed and reason&#xA;                for change."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup16"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="QTY" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Quantity"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Quantity"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="QTY"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FTX" eType="ecore:EClass commonDefinitions.ecore#//FreeText"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Free_text"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="FTX"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup10">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 10: RFF-TSR&#xA;                A group of segments to provide booking details&#xA;                (reference and type)."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup10"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="RFF"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TSR" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//TransportServiceRequirements"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Transport_service_requirements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="TSR"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup13">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 13: QTY-FTX&#xA;             A group of segments to specify, at the consignment level,&#xA;             the quantity manifested, quantity landed and reason for&#xA;             change."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup13"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="QTY" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Quantity"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Quantity"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="QTY"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FTX" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//FreeText"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Free_text"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="FTX"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup1">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 1:  RFF-DTM&#xA;       A group of segments to identify the unique reference number and&#xA;       date time details for the whole message."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup1"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="RFF"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DTM"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup15">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 15: GIS-DTM-DOC-PAC-MEA&#xA;                A group of segments specifying general indicators,&#xA;                associated date/time/details, documentary requirements&#xA;                and the weight and number of packages transported to&#xA;                another place in the port."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup15"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GIS" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//GeneralIndicator"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="General_indicator"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="GIS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DTM"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DOC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DocumentMessageDetails"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Document_message_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DOC"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PAC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Package"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Package"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="PAC"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MEA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Measurements"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Measurements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="MEA"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup3">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 3:  CTA-COM&#xA;          A group of segments to identify a contact and its&#xA;          communication related party."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup3"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CTA" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//ContactInformation"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Contact_information"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="CTA"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="COM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//CommunicationContact"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Communication_contact"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="COM"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup5">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 5:  EQD-TSR-MEA-DIM-SEL-NAD-GIS-SG6&#xA;       A group of segments to specify details of the equipment&#xA;       including information related to measurement, dimensions,&#xA;       seals, empty container responsible party, container quarantine&#xA;       indicator, as well as temperature/range and use indicator."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup5"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EQD" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//EquipmentDetails"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Equipment_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="EQD"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TSR" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//TransportServiceRequirements"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Transport_service_requirements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="TSR"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MEA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Measurements"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Measurements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="MEA"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DIM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Dimensions"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Dimensions"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="DIM"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SEL" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//SealNumber"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Seal_number"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="SEL"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NAD" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//NameAndAddress"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Name_and_address"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="NAD"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GIS" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//GeneralIndicator"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="General_indicator"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="GIS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup6" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup6" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_6"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
        <details key="segcode" value="TMP"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup8">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 8:  RFF-CNT-MOA-LOC-GIS-CUX-CPI-SG9-SG11-SG13-&#xA;                            SG14&#xA;          A group of segments specifying the details of each&#xA;          consignment."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup8"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="RFF"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CNT" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//ControlTotal"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Control_total"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="CNT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MOA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//MonetaryAmount"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Monetary_amount"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="MOA"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="LOC"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GIS" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//GeneralIndicator"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="General_indicator"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="GIS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CUX" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Currencies"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Currencies"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="CUX"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CPI" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//ChargePaymentInstructions"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Charge_payment_instructions"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="CPI"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup9" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup9" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_9"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
        <details key="segcode" value="TDT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup11" upperBound="99"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup11" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_11"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="group"/>
        <details key="segcode" value="NAD"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup13" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup13" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_13"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
        <details key="segcode" value="QTY"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup14" lowerBound="1"
        upperBound="9999" eType="ecore:EClass cuscar.ecore#//SegmentGroup14" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_14"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="group"/>
        <details key="segcode" value="GID"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value=""/>
      <details key="kind" value="mixed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CUSCAR" eType="ecore:EClass cuscar.ecore#//CUSCAR"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup7">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 7:  CNI-CNT-SG8&#xA;       A group of segments to provide details of the consignment(s)."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SegmentGroup7"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CNI" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//ConsignmentInformation"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Consignment_information"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="CNI"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CNT" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//ControlTotal"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Control_total"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
        <details key="segcode" value="CNT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup8" upperBound="9999"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup8" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_8"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="smooks-mapping-data">
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="group"/>
        <details key="segcode" value="RFF"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
