<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cuscar"
    nsURI="http://smooks.org/UNEDI/D99AUN/CUSCAR" nsPrefix="cuscar">
  <eAnnotations source="smooks-mapping-data">
    <details key="description.name" value="CUSCAR"/>
    <details key="description.version" value="D:99A:UN"/>
    <details key="delimeters.segment" value="&amp;#39;!$"/>
    <details key="delimeters.component" value=":"/>
    <details key="delimeters.field" value="+"/>
    <details key="delimeters.fieldRepeat"/>
    <details key="delimeters.escape" value="?"/>
    <details key="delimeters.ignoreCLRF" value="true"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup17">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 17: AUT-DTM-RFF&#xA;       A group of segments to specify the authentication of the&#xA;       message."/>
      <details key="xmlTag" value="Segment_group_17"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_17"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AUT" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//AuthenticationResult"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="AUT, Authentication result&#xA;          A segment to specify the results of the application of an&#xA;          authentication procedure, including the authenticity of&#xA;          sender to ensure integrity of data."/>
        <details key="xmlTag" value="Authentication_result"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Authentication_result"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DTM, Date/time/period&#xA;          A segment to specify the date/time/period when a message is&#xA;          authenticated."/>
        <details key="xmlTag" value="Date_time_period"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="RFF, Reference&#xA;          A segment to indicate any references to the authentication&#xA;          process."/>
        <details key="xmlTag" value="Reference"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup8">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 8:  RFF-CNT-MOA-LOC-GIS-CUX-CPI-SG9-SG11-SG13-&#xA;                            SG14&#xA;          A group of segments specifying the details of each&#xA;          consignment."/>
      <details key="xmlTag" value="Segment_group_8"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_8"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="RFF, Reference&#xA;             A segment to identify the bill number referring to the&#xA;             appropriate type of bill (e.g. master bill of lading,&#xA;             house bill of lading, straight air waybill)."/>
        <details key="xmlTag" value="Reference"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CNT" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//ControlTotal"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="CNT, Control total&#xA;             A segment to specify total consignment quantity and&#xA;             weight."/>
        <details key="xmlTag" value="Control_total"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Control_total"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MOA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//MonetaryAmount"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="MOA, Monetary amount&#xA;             A segment to specify the onward carriage shipment value,&#xA;             amount of insurance, value of Customs in-bond movement,&#xA;             declared value for Customs, declared value for carriage,&#xA;             no Customs value, transport charge amount, freight&#xA;             payment amount."/>
        <details key="xmlTag" value="Monetary_amount"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Monetary_amount"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="LOC, Place/location identification&#xA;             A segment to specify the Customs clearance office/place,&#xA;             place of origin of carriage, place of acceptance by&#xA;             importing carrier, place of ultimate destination of&#xA;             goods, place of transhipment, place of departure, place&#xA;             of customs examination and place/port of discharge."/>
        <details key="xmlTag" value="Place_location_identification"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GIS" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//GeneralIndicator"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="GIS, General indicator&#xA;             A segment to specify processing indicators such as&#xA;             import/export/transit indicator, container quarantine&#xA;             indicator, onward movement type indicator and status of&#xA;             the goods."/>
        <details key="xmlTag" value="General_indicator"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="General_indicator"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CUX" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Currencies"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="CUX, Currencies&#xA;             A segment to specify the default currency for the&#xA;             consignment, e.g. air waybill currency."/>
        <details key="xmlTag" value="Currencies"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Currencies"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CPI" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//ChargePaymentInstructions"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="CPI, Charge payment instructions&#xA;             A segment to specify the cargo category type, e.g. weight&#xA;             valuation, prepaid/collect and method of payment."/>
        <details key="xmlTag" value="Charge_payment_instructions"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Charge_payment_instructions"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup9" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup9" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 9:  TDT-LOC-DTM-MEA-SG10&#xA;             A group of segments to identify details of onward&#xA;             carriage for each consignment."/>
        <details key="xmlTag" value="Segment_group_9"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_9"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup11" upperBound="99"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup11" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 11: NAD-DTM-RFF-SG12&#xA;             A group of segments to identify the parties, contacts and&#xA;             related references and dates."/>
        <details key="xmlTag" value="Segment_group_11"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_11"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup13" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup13" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 13: QTY-FTX&#xA;             A group of segments to specify, at the consignment level,&#xA;             the quantity manifested, quantity landed and reason for&#xA;             change."/>
        <details key="xmlTag" value="Segment_group_13"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_13"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup14" lowerBound="1"
        upperBound="9999" eType="ecore:EClass cuscar.ecore#//SegmentGroup14" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 14: GID-PAC-HAN-FTX-MEA-MOA-SGP-DGS-PCI-&#xA;                               CST-LOC-TMD-SG15-SG16&#xA;             A group of segments specifying goods item details&#xA;             including number and type of packages, handling&#xA;             instructions, quantity variances, package identification,&#xA;             goods description, monetary amounts, measurements,&#xA;             indicators for split goods placement, indicator for&#xA;             dangerous goods, status of the goods, documents."/>
        <details key="xmlTag" value="Segment_group_14"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_14"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup11">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 11: NAD-DTM-RFF-SG12&#xA;             A group of segments to identify the parties, contacts and&#xA;             related references and dates."/>
      <details key="xmlTag" value="Segment_group_11"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_11"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NAD" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//NameAndAddress"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="NAD, Name and address&#xA;                A segment specifying the name and address of the&#xA;                consignor, shipper, notifier, consignee, empty&#xA;                container responsible party, nominated reporting&#xA;                agent, railway issuing waybill, and reporting party."/>
        <details key="xmlTag" value="Name_and_address"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Name_and_address"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DTM, Date/time/period&#xA;                A segment to specify date and/or time or period&#xA;                related to the party(s) identified in the NAD segment&#xA;                (e.g. date of birth)."/>
        <details key="xmlTag" value="Date_time_period"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="RFF, Reference&#xA;                A segment to identify a reference used by a party e.g.&#xA;                reporting party's reference number."/>
        <details key="xmlTag" value="Reference"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup12" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup12" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 12: CTA-COM&#xA;                A group of segments identifying a contact and its&#xA;                communication related to the party."/>
        <details key="xmlTag" value="Segment_group_12"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_12"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CUSCAR"/>
      <details key="kind" value="mixed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CUSCAR" eType="ecore:EClass cuscar.ecore#//CUSCAR"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup6">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 6:  TMP-RNG&#xA;          A group of segments to indicate temperature information."/>
      <details key="xmlTag" value="Segment_group_6"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_6"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TMP" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Temperature"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="TMP, Temperature&#xA;             A segment to specify temperature settings and indicator&#xA;             that refrigeration is in use."/>
        <details key="xmlTag" value="Temperature"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Temperature"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RNG" eType="ecore:EClass commonDefinitions.ecore#//RangeDetails"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="RNG, Range details&#xA;             A segment to specify a range of temperatures to be&#xA;             maintained on refrigeration equipment."/>
        <details key="xmlTag" value="Range_details"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Range_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup9">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 9:  TDT-LOC-DTM-MEA-SG10&#xA;             A group of segments to identify details of onward&#xA;             carriage for each consignment."/>
      <details key="xmlTag" value="Segment_group_9"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_9"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TDT" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//DetailsOfTransport"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="TDT, Details of transport&#xA;                A segment to specify the identity of the onward&#xA;                conveyance."/>
        <details key="xmlTag" value="Details_of_transport"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Details_of_transport"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="LOC, Place/location identification&#xA;                A segment to indicate locations relevant to the onward&#xA;                transport of the goods."/>
        <details key="xmlTag" value="Place_location_identification"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DTM, Date/time/period&#xA;                A segment to specify dates/times related to details of&#xA;                onward transport."/>
        <details key="xmlTag" value="Date_time_period"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MEA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Measurements"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="MEA, Measurements&#xA;                A segment to specify physical measurements, including&#xA;                dimension tolerances, weights and counts (e.g. vehicle&#xA;                weight details)."/>
        <details key="xmlTag" value="Measurements"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Measurements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup10" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup10" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 10: RFF-TSR&#xA;                A group of segments to provide booking details&#xA;                (reference and type)."/>
        <details key="xmlTag" value="Segment_group_10"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_10"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup10">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 10: RFF-TSR&#xA;                A group of segments to provide booking details&#xA;                (reference and type)."/>
      <details key="xmlTag" value="Segment_group_10"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_10"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="RFF, Reference&#xA;                   A segment to specify onward carriage control&#xA;                   number, onward carriage bond number and secondary&#xA;                   conveyance identification numbers."/>
        <details key="xmlTag" value="Reference"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TSR" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//TransportServiceRequirements"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="TSR, Transport service requirements&#xA;                   A segment to specify the contract and carriage&#xA;                   conditions and service and priority requirements&#xA;                   for the transport."/>
        <details key="xmlTag" value="Transport_service_requirements"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Transport_service_requirements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup13">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 13: QTY-FTX&#xA;             A group of segments to specify, at the consignment level,&#xA;             the quantity manifested, quantity landed and reason for&#xA;             change."/>
      <details key="xmlTag" value="Segment_group_13"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_13"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="QTY" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Quantity"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="QTY, Quantity&#xA;                A segment identifying quantity manifested and quantity&#xA;                landed."/>
        <details key="xmlTag" value="Quantity"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Quantity"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FTX" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//FreeText"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="FTX, Free text&#xA;                A segment to indicate the reason for change e.g.&#xA;                part/short/overshipped cargo."/>
        <details key="xmlTag" value="Free_text"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Free_text"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CUSCAR">
    <eAnnotations source="smooks-mapping-data">
      <details key="xmlTag" value="CUSCAR"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CUSCAR"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BGM" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//BeginningOfMessage"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="BGM, Beginning of message&#xA;       A segment to indicate the message name, type, number and&#xA;       functionality."/>
        <details key="xmlTag" value="Beginning_of_message"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Beginning_of_message"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DTM, Date/time/period&#xA;       A segment to indicate the date/time of message creation and the&#xA;       date and time of cargo report to Customs."/>
        <details key="xmlTag" value="Date_time_period"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="LOC, Place/location identification&#xA;       A segment to indicate the place and/or port where report is&#xA;       made."/>
        <details key="xmlTag" value="Place_location_identification"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="QTY" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Quantity"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="QTY, Quantity&#xA;       A segment to indicate the number of persons onboard."/>
        <details key="xmlTag" value="Quantity"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Quantity"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup1" upperBound="99"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup1" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 1:  RFF-DTM&#xA;       A group of segments to identify the unique reference number and&#xA;       date time details for the whole message."/>
        <details key="xmlTag" value="Segment_group_1"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_1"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup2" upperBound="99"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup2" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 2:  NAD-SG3&#xA;       A group of segments to identify contact and communication&#xA;       contact information related to the person responsible for the&#xA;       cargo reporting."/>
        <details key="xmlTag" value="Segment_group_2"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_2"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FTX" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//FreeText"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="FTX, Free text&#xA;       A segment to provide reason for change in report."/>
        <details key="xmlTag" value="Free_text"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Free_text"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup4" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup4" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 4:  TDT-LOC-DTM&#xA;       A group of segments to identify details of transport, locations&#xA;       and associated dates/times."/>
        <details key="xmlTag" value="Segment_group_4"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_4"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GIS" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//GeneralIndicator"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="GIS, General indicator&#xA;       A segment to specify the various customs processing indicators&#xA;       for the whole message."/>
        <details key="xmlTag" value="General_indicator"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="General_indicator"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup5" upperBound="9999"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup5" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 5:  EQD-TSR-MEA-DIM-SEL-NAD-GIS-SG6&#xA;       A group of segments to specify details of the equipment&#xA;       including information related to measurement, dimensions,&#xA;       seals, empty container responsible party, container quarantine&#xA;       indicator, as well as temperature/range and use indicator."/>
        <details key="xmlTag" value="Segment_group_5"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_5"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CNT" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//ControlTotal"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="CNT, Control total&#xA;       A segment to specify the total number of masters bills in the&#xA;       message."/>
        <details key="xmlTag" value="Control_total"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Control_total"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup7" upperBound="9999"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup7" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 7:  CNI-CNT-SG8&#xA;       A group of segments to provide details of the consignment(s)."/>
        <details key="xmlTag" value="Segment_group_7"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_7"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup17" eType="ecore:EClass cuscar.ecore#//SegmentGroup17"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 17: AUT-DTM-RFF&#xA;       A group of segments to specify the authentication of the&#xA;       message."/>
        <details key="xmlTag" value="Segment_group_17"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_17"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup16">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 16: QTY-FTX&#xA;                A group of segments to specify, at goods item level,&#xA;                the quantity manifested, quantity landed and reason&#xA;                for change."/>
      <details key="xmlTag" value="Segment_group_16"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_16"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="QTY" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Quantity"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="QTY, Quantity&#xA;                   A segment identifying quantity manifested and&#xA;                   quantity landed."/>
        <details key="xmlTag" value="Quantity"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Quantity"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FTX" eType="ecore:EClass commonDefinitions.ecore#//FreeText"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="FTX, Free text&#xA;                   A segment to indicate the reason for change e.g.&#xA;                   part/short/overshipped cargo."/>
        <details key="xmlTag" value="Free_text"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Free_text"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup3">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 3:  CTA-COM&#xA;          A group of segments to identify a contact and its&#xA;          communication related party."/>
      <details key="xmlTag" value="Segment_group_3"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_3"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CTA" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//ContactInformation"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="CTA, Contact information&#xA;             A segment to identify a person or department within a&#xA;             party."/>
        <details key="xmlTag" value="Contact_information"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Contact_information"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="COM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//CommunicationContact"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="COM, Communication contact&#xA;             A segment to identify the communication numbers of&#xA;             persons or department to whom communication should be&#xA;             directed."/>
        <details key="xmlTag" value="Communication_contact"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Communication_contact"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup4">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 4:  TDT-LOC-DTM&#xA;       A group of segments to identify details of transport, locations&#xA;       and associated dates/times."/>
      <details key="xmlTag" value="Segment_group_4"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_4"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TDT" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//DetailsOfTransport"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="TDT, Details of transport&#xA;          A segment to identify the primary identity of the conveyance&#xA;          e.g. voyage/flight number, vehicle number, railway car&#xA;          initials and numbers and name of vessel reference number."/>
        <details key="xmlTag" value="Details_of_transport"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Details_of_transport"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="LOC, Place/location identification&#xA;          A segment to indicate locations relevant to the details of&#xA;          transport, such as port/place of loading, port/place of&#xA;          discharge and port/place of initial arrival."/>
        <details key="xmlTag" value="Place_location_identification"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DTM, Date/time/period&#xA;          A segment to specify dates/times related to details of&#xA;          transport."/>
        <details key="xmlTag" value="Date_time_period"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup14">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 14: GID-PAC-HAN-FTX-MEA-MOA-SGP-DGS-PCI-&#xA;                               CST-LOC-TMD-SG15-SG16&#xA;             A group of segments specifying goods item details&#xA;             including number and type of packages, handling&#xA;             instructions, quantity variances, package identification,&#xA;             goods description, monetary amounts, measurements,&#xA;             indicators for split goods placement, indicator for&#xA;             dangerous goods, status of the goods, documents."/>
      <details key="xmlTag" value="Segment_group_14"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_14"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GID" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//GoodsItemDetails"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="GID, Goods item details&#xA;                A segment identifying the line item number, as well as&#xA;                number and type of packages."/>
        <details key="xmlTag" value="Goods_item_details"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Goods_item_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PAC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Package"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="PAC, Package&#xA;                A segment identifying the level of packaging."/>
        <details key="xmlTag" value="Package"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Package"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="HAN" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//HandlingInstructions"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="HAN, Handling instructions&#xA;                A segment identifying handling instructions."/>
        <details key="xmlTag" value="Handling_instructions"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Handling_instructions"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FTX" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//FreeText"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="FTX, Free text&#xA;                A segment to identify the description of goods."/>
        <details key="xmlTag" value="Free_text"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Free_text"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MEA" upperBound="99" eType="ecore:EClass commonDefinitions.ecore#//Measurements"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="MEA, Measurements&#xA;                A segment to identify the goods item gross/net weight."/>
        <details key="xmlTag" value="Measurements"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="99"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Measurements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MOA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//MonetaryAmount"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="MOA, Monetary amount&#xA;                Values per item."/>
        <details key="xmlTag" value="Monetary_amount"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Monetary_amount"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SGP" upperBound="9999"
        eType="ecore:EClass commonDefinitions.ecore#//SplitGoodsPlacement" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="SGP, Split goods placement&#xA;                A segment to indicate the placement of goods in one or&#xA;                more containers."/>
        <details key="xmlTag" value="Split_goods_placement"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Split_goods_placement"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DGS" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DangerousGoods"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DGS, Dangerous goods&#xA;                A segment to identify dangerous goods."/>
        <details key="xmlTag" value="Dangerous_goods"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Dangerous_goods"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PCI" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//PackageIdentification"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="PCI, Package identification&#xA;                A segment identifying shipping marks."/>
        <details key="xmlTag" value="Package_identification"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Package_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CST" eType="ecore:EClass commonDefinitions.ecore#//CustomsStatusOfGoods"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="CST, Customs status of goods&#xA;                A segment to identify Harmonized System codes related&#xA;                to each goods item."/>
        <details key="xmlTag" value="Customs_status_of_goods"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Customs_status_of_goods"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LOC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//PlaceLocationIdentification"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="LOC, Place/location identification&#xA;                A segment to indicate the location onboard the&#xA;                conveyance where the goods and/or ship's stores is&#xA;                stored."/>
        <details key="xmlTag" value="Place_location_identification"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Place_location_identification"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TMD" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//TransportMovementDetails"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="TMD, Transport movement details&#xA;                A segment used to describe specific transport movement&#xA;                details for goods related to the transportation&#xA;                information."/>
        <details key="xmlTag" value="Transport_movement_details"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Transport_movement_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup15" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup15" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 15: GIS-DTM-DOC-PAC-MEA&#xA;                A group of segments specifying general indicators,&#xA;                associated date/time/details, documentary requirements&#xA;                and the weight and number of packages transported to&#xA;                another place in the port."/>
        <details key="xmlTag" value="Segment_group_15"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_15"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup16" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup16" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 16: QTY-FTX&#xA;                A group of segments to specify, at goods item level,&#xA;                the quantity manifested, quantity landed and reason&#xA;                for change."/>
        <details key="xmlTag" value="Segment_group_16"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_16"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup7">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 7:  CNI-CNT-SG8&#xA;       A group of segments to provide details of the consignment(s)."/>
      <details key="xmlTag" value="Segment_group_7"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_7"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CNI" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//ConsignmentInformation"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="CNI, Consignment information&#xA;          A segment to sequentially number master bills reported in a&#xA;          multi-consignment message. For a single consignment message,&#xA;          this sequence number will always be 1."/>
        <details key="xmlTag" value="Consignment_information"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Consignment_information"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CNT" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//ControlTotal"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="CNT, Control total&#xA;          A segment to specify the total number of house bills&#xA;          reported under one master bill."/>
        <details key="xmlTag" value="Control_total"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Control_total"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup8" upperBound="9999"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup8" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 8:  RFF-CNT-MOA-LOC-GIS-CUX-CPI-SG9-SG11-SG13-&#xA;                            SG14&#xA;          A group of segments specifying the details of each&#xA;          consignment."/>
        <details key="xmlTag" value="Segment_group_8"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9999"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_8"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup5">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 5:  EQD-TSR-MEA-DIM-SEL-NAD-GIS-SG6&#xA;       A group of segments to specify details of the equipment&#xA;       including information related to measurement, dimensions,&#xA;       seals, empty container responsible party, container quarantine&#xA;       indicator, as well as temperature/range and use indicator."/>
      <details key="xmlTag" value="Segment_group_5"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_5"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EQD" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//EquipmentDetails"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="EQD, Equipment details&#xA;          A segment to specify the type of equipment, empty container&#xA;          indicator, and container number."/>
        <details key="xmlTag" value="Equipment_details"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Equipment_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TSR" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//TransportServiceRequirements"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="TSR, Transport service requirements&#xA;          A segment to specify the contract, carriage conditions,&#xA;          service and priority requirements for the transport."/>
        <details key="xmlTag" value="Transport_service_requirements"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Transport_service_requirements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MEA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Measurements"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="MEA, Measurements&#xA;          A segment to specify the measurements details for the&#xA;          equipment."/>
        <details key="xmlTag" value="Measurements"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Measurements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DIM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Dimensions"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DIM, Dimensions&#xA;          A segment to specify the dimensions."/>
        <details key="xmlTag" value="Dimensions"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Dimensions"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SEL" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//SealNumber"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="SEL, Seal number&#xA;          A segment to specify the seal number."/>
        <details key="xmlTag" value="Seal_number"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Seal_number"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NAD" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//NameAndAddress"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="NAD, Name and address&#xA;          A segment to specify the name and address of the empty&#xA;          container responsible party."/>
        <details key="xmlTag" value="Name_and_address"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Name_and_address"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GIS" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//GeneralIndicator"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="GIS, General indicator&#xA;          A segment to specify the container quarantine indicator."/>
        <details key="xmlTag" value="General_indicator"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="General_indicator"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup6" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup6" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 6:  TMP-RNG&#xA;          A group of segments to indicate temperature information."/>
        <details key="xmlTag" value="Segment_group_6"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_6"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup1">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 1:  RFF-DTM&#xA;       A group of segments to identify the unique reference number and&#xA;       date time details for the whole message."/>
      <details key="xmlTag" value="Segment_group_1"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_1"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RFF" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//Reference"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="RFF, Reference&#xA;          A segment to provide the unique reference number for the&#xA;          message, e.g. manifest number."/>
        <details key="xmlTag" value="Reference"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Reference"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DTM, Date/time/period&#xA;          A segment to indicate the date/time of the reference number&#xA;          for the message."/>
        <details key="xmlTag" value="Date_time_period"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup15">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 15: GIS-DTM-DOC-PAC-MEA&#xA;                A group of segments specifying general indicators,&#xA;                associated date/time/details, documentary requirements&#xA;                and the weight and number of packages transported to&#xA;                another place in the port."/>
      <details key="xmlTag" value="Segment_group_15"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_15"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GIS" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//GeneralIndicator"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="GIS, General indicator&#xA;                   A segment to indicate other government requirements&#xA;                   (e.g. government quarantine indicator) to be met&#xA;                   prior to onward movement and status of the goods."/>
        <details key="xmlTag" value="General_indicator"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="General_indicator"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DTM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DateTimePeriod"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DTM, Date/time/period&#xA;                   A segment to specify a date/time related to the&#xA;                   whole group."/>
        <details key="xmlTag" value="Date_time_period"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Date_time_period"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DOC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//DocumentMessageDetails"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="DOC, Document/message details&#xA;                   A segment to indicate other government agency&#xA;                   documentary requirements which must be met prior to&#xA;                   onward movement."/>
        <details key="xmlTag" value="Document_message_details"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Document_message_details"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PAC" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Package"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="PAC, Package&#xA;                   A segment to indicate the number of packages&#xA;                   transported to another place within the port."/>
        <details key="xmlTag" value="Package"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Package"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MEA" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//Measurements"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="MEA, Measurements&#xA;                   A segment to indicate the gross weight of the&#xA;                   packages transported to another place within the&#xA;                   port."/>
        <details key="xmlTag" value="Measurements"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Measurements"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup12">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 12: CTA-COM&#xA;                A group of segments identifying a contact and its&#xA;                communication related to the party."/>
      <details key="xmlTag" value="Segment_group_12"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_12"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CTA" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//ContactInformation"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="CTA, Contact information&#xA;                   A segment to identify a person or department within&#xA;                   a party."/>
        <details key="xmlTag" value="Contact_information"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Contact_information"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="COM" upperBound="9" eType="ecore:EClass commonDefinitions.ecore#//CommunicationContact"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="COM, Communication contact&#xA;                   A segment to identify the communication numbers of&#xA;                   persons or department to whom communication should&#xA;                   be directed."/>
        <details key="xmlTag" value="Communication_contact"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Communication_contact"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentGroup2">
    <eAnnotations source="smooks-mapping-data">
      <details key="documentation" value="Segment group 2:  NAD-SG3&#xA;       A group of segments to identify contact and communication&#xA;       contact information related to the person responsible for the&#xA;       cargo reporting."/>
      <details key="xmlTag" value="Segment_group_2"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Segment_group_2"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NAD" lowerBound="1" eType="ecore:EClass commonDefinitions.ecore#//NameAndAddress"
        containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="NAD, Name and address&#xA;          A segment to identify the person or party reporting the&#xA;          cargo."/>
        <details key="xmlTag" value="Name_and_address"/>
        <details key="minOccurs" value="1"/>
        <details key="maxOccurs" value="1"/>
        <details key="type" value="segment"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Name_and_address"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentGroup3" upperBound="9"
        eType="ecore:EClass cuscar.ecore#//SegmentGroup3" containment="true">
      <eAnnotations source="smooks-mapping-data">
        <details key="documentation" value="Segment group 3:  CTA-COM&#xA;          A group of segments to identify a contact and its&#xA;          communication related party."/>
        <details key="xmlTag" value="Segment_group_3"/>
        <details key="minOccurs" value="0"/>
        <details key="maxOccurs" value="9"/>
        <details key="type" value="group"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Segment_group_3"/>
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
